//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        public int Id { get; set; }

        [Required]
        [StringLength(5)]
        public string uname { get; set; }

        [Required]
        public string uemail { get; set; }
        public string upass { get; set; }
        public string ugender { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> cityid { get; set; }
        public string ueducation { get; set; }
        public string uphoto { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> regDate { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
